# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config.json
---
version: "1"

global:
  ##  There are many options for default-command, like 'snapshots', 'backup', and 'prune'
  default-command: backup
  initialize: false
  priority: low
  min-memory: 100

## Defaults that profiles can inherit with 'inherit: default'
default:
  repository: "local:/path/to/restic-repo"
  ## Path to a file containing the path to your restic repository
  # repository-file: "/path/to/restic_repo_file"
  ## Command to run to get password (i.e. read from vault)
  # password-command: ""
  ## Path to a file with your restic repository password
  password-file: "/path/to/restic_pw"

  forget:
    keep-last: 2
    keep-hourly: 24
    keep-daily: 7
    keep-weekly: 4
    keep-tag:
      - forever
    prune: true
    tag:
      - resticprofile

  backup:
    verbose: false
    one-file-system: false
    read-concurrency: 2
    skip-if-unchanged: true
    exclude:
      - ".tmp/"
      - ".cache/"
    exclude-file:
      - "/path/to/resticignore"
    exclude-cloud-files: true
    # exclude-if-larger-than: ""
    ## Options are 'host', 'paths', 'tags', and can be combined
    #  with a comma, like: 'host,paths'
    group-by: "host,paths"

  check:
    schedule: "weekly"
    schedule-after-network-online: false
    schedule-ignore-on-battery: false
    schedule-ignore-on-battery-less-than: 20
    read-data: true
    with-cache: false

  cache:
    cleanup: false
    max-age: 30
    no-size: false

  no-error-on-warning: true

## Example rclone backup
rclone_backup:
  inherit: default
  repository: "rclone:your-remote:restic-backups"
  backup:
    source:
      - "/home/username"
  tags:
    - rclone
    - home
    - userland
  env:
    ## Set path to rclone.conf file. Looks in ~/.config/rclone/rclone.conf by default
    RCLONE_CONFIG: "{{ .Env.RCLONE_CONFIG | or \"~/.config/rclone/rclone.conf\" }}"
